### ISSUE TITLE
@ sourceMappingURL comment

### ISSUE THREAD

**Issue by axelhzf** [gmarty/grunt-closure-compiler#7]
Hi

I'm working with source maps and I have a problem.

The closure compile didn't add a comment like this to te generated file.

``` javascript
//@ sourceMappingURL=app.map
```

This comment is necessary when debugging with chrome or firefox to show the original files.
I haven't found an options to tell the compiler to generate that.

 Maybe it could be an option of this plugin, since it know the generated file path and the source map path.  It is only necessary to append a comment like that at the end of the file.

**Comment by gmarty** [comment]
Hi!
This issue is not directly related to this plugin, so I suggest to ask your question to https://groups.google.com/forum/?fromgroups=#!forum/closure-compiler-discuss

But AFAIK, the compiler is not supposed to add the `sourceMappingURL` annotation to the minified script.

What I suggest is to use the `output_wrapper` option and pass to the plugin options similar to this:

``` javascript
options: {
  create_source_map: 'source_map.json',
  output_wrapper: '"%output%//@ sourceMappingURL=source_map.json"'
}
```

The `%output%` will expand to the minified JavaScript source, thus appending an extra comment on the output. You'll just have to match the souce map file location in `create_source_map` and `output_wrapper`.

It worked for me, so I'm closing this issue. But let me know if anything goes wrong.
